const wordsDatabaseEasy = [
    "over", "large", "just", "few", "only", "come", "all", "tell",
    "say", "lead", "they", "see", "so", "face", "home", "fact",
    "act", "well", "so", "turn", "thing", "we", "life", "because", "night",
    "run", "play", "is", "not", "a", "game", "how", "what", "when", "of",
    "about", "about", "the", "be", "of", "and", "a", "to", "in", "he", "have", "it", 
    "that", "for", "they", "with", "as", "not", "on", "she", "at", "by", "this", "we", 
    "you", "do", "but", "from", "or", "which", "one", "would", "all", "will", "there", "say",
    "who", "make", "when", "can", "more", "if", "no", "man", "out", "other", "so",
    "what", "time", "up", "go", "about", "than", "into", "could", "state", "only",
    "new", "year", "some", "take", "come", "these", "know", "see", "use", "get",
    "like", "then", "first", "any", "work", "now", "may", "such", "give", "over",
    "think", "most", "even", "find", "day", "also", "after", "way", "many", "must",
    "look", "before", "great", "back", "through", "long", "where", "much", "should",
    "well", "people", "down", "own", "just", "because", "good", "each", "those",
    "feel", "seem", "how", "high", "too", "place", "little", "world", "very", "still",
    "nation", "hand", "old", "life", "tell", "write", "become", "under", "last",
    "right", "move", "thing", "general", "school", "never", "same", "another", "begin",
    "while", "number", "part", "turn", "real", "leave", "might", "want", "point",
    "form", "off", "child", "few", "small", "since", "against", "ask", "late", "home",
    "interest", "large", "person", "end", "open", "public", "follow", "during", "present",
    "without", "again", "hold", "govern", "around", "possible", "head", "consider",
    "word", "program", "problem", "however", "lead", "system", "set", "order", "eye",
    "plan", "run", "keep", "face", "fact", "group", "play", "stand", "increase", "early",
    "course", "change", "help", "line", "a"
];

const wordsDatabaseMedium = [
    "abundant", "access", "achieve", "gather", "difficulty", "support", "unclear", "worried",
    "hard", "clear", "confident", "blend", "confirm", "kind", "rules", "friendship",
    "trigger", "merge", "complicated", "together", "remember", "complete", "agree", "friendly",
    "talk", "friendly", "tricky", "together", "complicated", "growing", "harmful", "criticize",
    "show", "behavior", "copy", "hardworking", "dislike", "explain", "spread", "different",
    "detail", "wellspoken", "understanding", "try", "mystery", "count", "shortlived", "unclear",
    "knowledgeable", "polite", "worsen", "typify", "speedup", "explain", "praise", "joking",
    "possible", "change", "courage", "encourage", "save", "sociable", "random", "order",
    "suggestion", "make", "unintentional", "doesnt", "native",
    "random", "honest", "look", "indecisive", "sidebyside", "grieve", "lavish", "lazy",
    "generous", "obvious", "wander", "careful", "average", "calm", "repetitive", "many",
    "care", "unaware", "oldfashioned", "threatening", "luxurious", "traditional", "contradiction", "observant",
    "continue", "relevant", "realistic", "risky", "trouble", "common", "impressive", "skilled",
    "plentiful", "creative", "prosperous", "wise", "strong", "dilemma", "hungry", "scold",
    "make", "repeat", "let", "bounce", "respect", "persuasive", "basic", "wise",
    "examine", "fortunate", "doubtful", "occasional", "stoic", "secretive", "susceptible", "silent",
    "touchable", "weak", "everywhere", "agreed", "never", "unjustified", "respected", "able",
    "alert", "prove", "skilled", "easily", "funny", "enthusiastic",
    "over", "large", "just", "few", "only", "come", "all", "tell",
    "say", "lead", "they", "see", "so", "face", "home", "fact",
    "act", "well", "so", "turn", "thing", "we", "life", "because", "night",
    "run", "play", "is", "not", "a", "game", "how", "what", "when", "of",
    "about", "about", "the", "be", "of", "and", "a", "to", "in", "he", "have", "it", 
    "that", "for", "they", "with", "as", "not", "on", "she", "at", "by", "this", "we", 
    "you", "do", "but", "from", "or", "which", "one", "would", "all", "will", "there", "say",
    "who", "make", "when", "can", "more", "if", "no", "man", "out", "other", "so",
    "what", "time", "up", "go", "about", "than", "into", "could", "state", "only",
    "new", "year", "some", "take", "come", "these", "know", "see", "use", "get",
    "like", "then", "first", "any", "work", "now", "may", "such", "give", "over",
    "think", "most", "even", "find", "day", "also", "after", "way", "many", "must",
    "look", "before", "great", "back", "through", "long", "where", "much", "should",
    "well", "people", "down", "own", "just", "because", "good", "each", "those",
    "feel", "seem", "how", "high", "too", "place", "little", "world", "very", "still",
    "nation", "hand", "old", "life", "tell", "write", "become", "under", "last",
    "right", "move",
    "thing", "general", "school", "never", "same", "another", "begin",
    "while", "number", "part", "turn", "real", "leave", "might", "want", "point",
    "form", "off", "child", "few", "small", "since", "against", "ask", "late", "home",
    "interest", "large", "person", "end", "open", "public", "follow", "during", "present",
    "without", "again", "hold", "govern", "around", "possible", "head", "consider",
    "word", "program", "problem", "however", "lead", "system", "set", "order", "eye",
    "plan", "run", "keep", "face", "fact", "group", "play", "stand", "increase", "early",
    "course", "change", "help", "line", "a"
];

const wordsDatabaseHard = [
    "abhorrent", "acrimonious", "affluent", "ambivalent", "anachronistic", "antagonize", "apocryphal", "auspicious",
    "belligerent", "cacophony", "capitulate", "circumlocution", "cognizant", "deleterious", "desultory", "dichotomy",
    "disparage", "ebullient", "efficacious", "equanimity", "exacerbate", "exonerate", "extemporaneous", "facetious",
    "fastidious", "flagrant", "garrulous", "gregarious", "hackneyed", "idiosyncratic", "indignant", "inimical",
    "insidious", "intransigent", "inveterate", "juxtaposition", "laconic", "lugubrious", "magnanimous", "malfeasance",
    "mendacious", "nefarious", "obfuscate", "ostentatious", "paradigm", "pariah", "pensive", "pernicious",
    "pertinacious", "plethora", "predilection", "prevaricate", "proclivity", "propensity", "pulchritude", "querulous",
    "quixotic", "recalcitrant", "recidivism", "recondite", "redolent", "replete", "repudiate", "sagacious",
    "salient", "sanguine", "scurrilous", "solipsistic", "stalwart", "supercilious", "sycophant", "tantamount",
    "tenuous", "trenchant", "ubiquitous", "umbrage", "unctuous", "unilateral", "usurp", "vacillate",
    "venerable", "vicissitude", "vitriolic", "vociferous", "wheedle", "winsome", "zealot", "zeitgeist",
    "over", "large", "just", "few", "only", "come", "all", "tell",
    "say", "lead", "they", "see", "so", "face", "home", "fact",
    "act", "well", "so", "turn", "thing", "we", "life", "because", "night",
    "run", "play", "is", "not", "a", "game", "how", "what", "when", "of",
    "about", "about", "the", "be", "of", "and", "a", "to", "in", "he", "have", "it", 
    "that", "for", "they", "with", "as", "not", "on", "she", "at", "by", "this", "we", 
    "you", "do", "but", "from", "or", "which", "one", "would", "all", "will", "there", "say",
    "who", "make", "when", "can", "more", "if", "no", "man", "out", "other", "so",
    "what", "time", "up", "go", "about", "than", "into", "could", "state", "only",
    "new", "year", "some", "take", "come", "these", "know", "see", "use", "get",
    "like", "then", "first", "any", "work", "now", "may", "such", "give", "over",
    "think", "most", "even", "find", "day", "also", "after", "way", "many", "must",
    "look", "before", "great", "back", "through", "long", "where", "much", "should",
    "well", "people", "down", "own", "just", "because", "good", "each", "those",
    "feel", "seem", "how", "high", "too", "place", "little", "world", "very", "still",
    "nation", "hand", "old", "life", "tell", "write", "become", "under", "last",
    "right", "move",
    "thing", "general", "school", "never", "same", "another", "begin",
    "while", "number", "part", "turn", "real", "leave", "might", "want", "point",
    "form", "off", "child", "few", "small", "since", "against", "ask", "late", "home",
    "interest", "large", "person", "end", "open", "public", "follow", "during", "present",
    "without", "again", "hold", "govern", "around", "possible", "head", "consider",
    "word", "program", "problem", "however", "lead", "system", "set", "order", "eye",
    "plan", "run", "keep", "face", "fact", "group", "play", "stand", "increase", "early",
    "course", "change", "help", "line", "a"
];
